### PR TITLE
Add MorphToMany Relation to Inline Types

### PR DESCRIPTION
**Pull request by mgarciadelojo**
Although you told me a big refactoring on the PHP part is on the road, I created this new inline relationship to allow my users to have embeds when using morph relationships.

### CODE REVIEW

**Comment by lazychaser** [comment]
Can you provide a use case for this? MorphToMany is just like belongsToMany and should not be editable. The reason is that resource is shared among different models. I believe that if you need to inline something other than HasOne/HasMany (and morphable alternatives), you have an app design issue.

**Comment by mgarciadelojo** [comment]
Maybe you are right, so, the only option would be a problem with my relations. The thing is I have a media model, in which I want to store images (just like Wordpress does). Many other models have a MorphToMany relationship to store many media.

The problem is when I edit a record, and click Save, the original data is shown, so, the save action can't be done. This is making me crazy, because users can't save changes into the DB.

**Comment by lazychaser** [comment]
Mm, for media objects I use single table inheritance pattern (meaning that you can store any type of media in a single table). With this aproach you don't need to use morphable relations at all.

I can say that morphable relations are just too hard to be used properly and I try to avoid using them at all.

**Comment by lazychaser** [comment]
Ah, in this case it's ok to use polymorphic relation. And in Cruddy you can use `relates` field. It allows creating and editing models from the drop down.

**Comment by mgarciadelojo** [comment]
Yeah, I know. But I would like to use embed relations instead of relates because in that case users can see images in a more visual way than a list of random names :)

is there any other option to achieve that?

Thanks!

**Comment by lazychaser** [comment]
Yep, see #118

**Comment by mgarciadelojo** [comment]
Ok, that's what I wanted! Thanks! I close the PR.

**Pull request closed without merging**
